### ISSUE TITLE
Bashism in build-all.sh goes wrong when /bin/sh is not bash

### ISSUE THREAD

**Issue by DurvalMenezes** [SiteRelEnby/anduril2#1]
This happens on my Devuan Chimaera (systemd Debian Stretch) build system, but will also happen on any system where /bin/sh is not a hard/symlink to bash: 

```
$ build-all.sh
    [...]
    ./build-all.sh: 41: [[: not found
    [...]
```

This happens because this fork introduced "[[" (which was not used in upstream) but failed to change the `#!/bin/sh` to `#!/bin/bash`; this results in the above error as the standard Bourne shell does not support `[[`. 

This causes the inadvertent renaming of ".hex" files to "..hex". 

The preferred fix IMHO for this is instead to change the (single)  `[[` (and the corresponding `]]`) to the more universal `[` and `]`, this way it avoids introducing `bash` as a dependency:
 
```
--- ./build-all.sh      2023-04-08 14:33:12.994050990 -0400
+++ ./build-all.sh.orig-20230408L14901  2023-04-07 21:57:14.000000000 -0400
@@ -38,7 +38,7 @@
 
   # track result, and rename compiled files
   if [ 0 = $? ] ; then
-    if [ -z "${COMMITHASH}" ]
+    if [[ -z "${COMMITHASH}" ]]
     then
       mv -f "$UI".hex "$UI".$NAME.hex
     else
```

Sorry for not submitting this fix the proper way (ie via a PR) but I'm really busy here (local tax season) and just wanted to point what I think is the right direction.

**Comment by SiteRelEnby** [comment]
https://github.com/SiteRelEnby/anduril2/commit/0669bfad99610ab6a165739b6e78181abb291036

Overall the build scripts still need some attention but I've had enough questions about building this (and a lot of the default builds are broken) that I might work on it next.

**Comment by DurvalMenezes** [comment]
Just tested with your new tree (as per my comment [here](https://www.reddit.com/r/flashlight/comments/12c64xz/comment/jh1kt0m/?context=1)) and I can confirm it's fixed. Thanks!
