### ISSUE TITLE
dependency on docker

### ISSUE THREAD

**Issue by gretel** [SiteRelEnby/anduril2#3]
```
$ ./build.sh
./build.sh: line 21: docker: command not found
```

i'd like to build the code locally, that is without docker. is that supported or possible by a change? regards

**Comment by SiteRelEnby** [comment]
if you have avr-gcc and the full build toolchain installed you can directly call `spaghetti-monster/anduril/build-all.sh` (TK's script from upstream), `build.sh` is something I mostly included for my own convenience as I prefer to build using docker. I should probably rework build.sh to handle more edge cases, hopefully when I can merge commits to the main repo more directly as the whole build toolchain needs some work.

**Comment by SiteRelEnby** [comment]
https://github.com/SiteRelEnby/anduril2/commit/13de06843e04a91d3c22eff0c00cc7929c759a36

**Comment by gretel** [comment]
```
$ ./build.sh
docker not installed. This script is mostly a convenience script to use the docker builder - to run a build locally, avr-gcc needs to be installed, then run spaghetti-monster/anduril/build-all.sh directly
see: https://github.com/SiteRelEnby/anduril2/issues/3
For more info on installing the build toolchain locally, see https://budgetlightforum.com/t/anduril-2/62656/328
```

nice, thank you.
