### ISSUE TITLE
'build-all.sh' depends on bash but shebangs sh

### ISSUE THREAD

**Issue by gretel** [SiteRelEnby/anduril2#4]
```shell
$ ./build-all.sh
...
./build-all.sh: 45: [[: not found
```

either the script has to stick with what is supported in `sh` (use `test` or `[` instead of `[[`) or the shebang has to be changed to:

```shell
#!/usr/bin/env bash
```

regards

**Comment by SiteRelEnby** [comment]
Fixed.

That particular issue is from ToyKeeper's upstream repo, I've got a lot of improvements to build scripts to submit when she moves the repo to git, which I've held off on as I'm trying to maintain compatibility with her repo as much as possible.
